spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_LOWER=true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      schema-locations:
        - classpath:/sql/schema.sql
        - classpath:org/springframework/security/core/userdetails/jdbc/users.ddl
      #      data-locations: classpath:/sql/data.sql
      encoding: UTF-8
  output:
    ansi:
      enabled: DETECT
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.gradle: ERROR
    io.spring: ERROR