server:
  port: ${hrmanager.server.port}
  ssl:
    certificate: ${hrmanager.keystore.certificate}
    certificate-private-key: ${hrmanager.keystore.private-key}
logging.file.name: ${hrmanager.logging.file}
