spring:
  datasource:
    url: jdbc:h2:file:./h2db;DB_CLOSE_ON_EXIT=false;DATABASE_TO_LOWER=true
  jpa:
    properties:
      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy
#        hbm2ddl:
#          auto: create-drop
        show_sql: true
        format_sql: true
        #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.MariaDBDialect
  output:
    ansi:
      enabled: DETECT
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.gradle: ERROR
    io.spring: ERROR
#    org:
#      gradle: ERROR
#      springframework: info
#      hibernate:
#        type: trace