spring:
  datasource:
    url: jdbc:h2:file:./h2db;DB_CLOSE_ON_EXIT=false;DATABASE_TO_LOWER=true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: DETECT
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.gradle: ERROR
    io.spring: ERROR