CREATE TABLE IF NOT EXISTS employee_status (
                                                 es_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '사원 상태 ID',
                                                 emp_id BIGINT NOT NULL COMMENT '사원 ID',
                                                 es_ty VARCHAR(90) NOT NULL COMMENT '상태 유형',
                                                 start_date DATE NOT NULL COMMENT '시작일',
                                                 end_date DATE NULL COMMENT '종료일',
                                                 scheduled_end_date DATE NULL COMMENT '예정 종료일',
                                                 create_dt DATETIME NOT NULL COMMENT '생성일',
                                                 enabled BOOLEAN NOT NULL COMMENT '사용가능',
                                                 PRIMARY KEY (es_id)
);

TRUNCATE TABLE employee_status;