CREATE TABLE IF NOT EXISTS non_working_days_calendar (
                                                         nwd_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                         parent_id BIGINT NULL,
                                                         annual_id BIGINT NULL,
                                                         weekly_id BIGINT NULL,
                                                         temp_id BIGINT NULL,
                                                         nwd_date DATE NOT NULL,
                                                         enabled BOOLEAN NOT NULL,
                                                         PRIMARY KEY (nwd_id))
;

TRUNCATE TABLE non_working_days_calendar;

INSERT INTO non_working_days_calendar(nwd_id,
                                      annual_id,
                                      nwd_date,
                                    enabled)
VALUES (1,
        4,
        '2022-03-01',
        TRUE);